# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files for dependency installation
COPY package.json package-lock.json ./

# Install dependencies with build cache
RUN --mount=type=cache,target=/root/.npm npm ci

# Copy source code and configuration
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm run build

FROM node:20-alpine AS release

WORKDIR /app

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

# Copy package files
COPY package.json package-lock.json ./

# Install production dependencies only
RUN npm ci --ignore-scripts --omit=dev && \
    npm cache clean --force

# Copy built application from builder
COPY --from=builder /app/dist ./dist

# Change ownership to non-root user
RUN chown -R nodejs:nodejs /app

USER nodejs

EXPOSE 8080

ENTRYPOINT ["node", "dist/main/index.js"]
